import type { Metadata } from "next";
import {Geist_Mono, Unbounded } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";

const unbounded = Unbounded({
  variable: "--font-unbounded",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.variable} ${unbounded.variable}`}
      >
        {children}
        <Nav />
      </body>
    </html>
  );
}
